kind: pipeline
type: docker
name: server

steps:
  - name: pre-build
    image: alpine
    environment:
      CONFIG:
        from_secret: config-file
    commands:
      - cd ./Server/src
      - echo $${CONFIG} > config.json
  - name: build
    image: plugins/docker
    settings:
      registry:
        from_secret: docker-registry
      username:
        from_secret: docker-username
      password:
        from_secret: docker-password
      repo:
        from_secret: docker-repo
      tags: latest
      dry_run: false
      purge: true
      context: ./Server
      dockerfile: ./Server/Dockerfile

trigger:
  event:
    - custom
    - push
    - pull_request

---
kind: pipeline
type: docker
name: after-server

steps:
  - name: deploy-to-server
    image: plugins/webhook
    settings:
      urls:
        from_secret: webhook

depends_on:
  - server

trigger:
  event:
    - custom
    - push
    - pull_request
